-- thanks for downloading my content! :D
-- hope you find it helpful
--
--
-- if you are having trouble using this contact me at discord: HAndLol#6848
--
-- feedback is appreciated! (write me a review *wink* *wink*)
--
-- you can modify and publish this content as your own, crediting me is really appreciated but not necessary :)
--
--
-------------
-- changelog:
--	1.0.0
--		the release!
--
--
-------------
-- known issues:
--	UI cant be resized
--
--
-------------
-- credits and ascii art!
--
--
--            ___
--           (___)
--            : :
--           /   \
--         _________
--       ,"  '    ',",
--      , '    '    , ,
--      (  ,   ' '    )
--       )  '   ,    (
--      /     '    ,  \
--     : , '  ,      , :
--     |   ,     '  ,  |
--     |_______________|
--     |the content was|
--     |      ---      |
--     |    made by    |
--     |    HAndLol    |
--     |      ---      |
--     |_______________|
--     |'    ,  ,    , |
--     |'  '    ,    , |
--     : ,' _' , '_ , ':
--     \___/ \___/ \___/
--
--
-- thanks to:
--	WaveParadigm
--		for making "Biplane Controls", it was used when testing my script
--	AphrimCreates
--		for making "Drivable Jeep", it was used when testing my script as well