Assets {
  Id: 13018704765523888270
  Name: "RecipeData"
  PlatformAssetType: 3
  TextAsset {
    CustomParameters {
      Overrides {
        Name: "cs:Name"
        String: ""
      }
      Overrides {
        Name: "cs:UniqueStorageId"
        Int: 0
      }
      Overrides {
        Name: "cs:Tags"
        String: ""
      }
      Overrides {
        Name: "cs:CraftSeconds"
        Float: 0
      }
      Overrides {
        Name: "cs:OutputText"
        String: ""
      }
      Overrides {
        Name: "cs:IconCameraId"
        String: ""
      }
      Overrides {
        Name: "cs:IconAsset"
        AssetReference {
          Id: 11569295798238027817
        }
      }
      Overrides {
        Name: "cs:IsKitbashed2DIcon"
        Bool: false
      }
      Overrides {
        Name: "cs:Is3DIcon"
        Bool: false
      }
      Overrides {
        Name: "cs:IsImageIcon"
        Bool: true
      }
      Overrides {
        Name: "cs:IconCameraId:tooltip"
        String: "If \"Is3DIcon\" is true, this should match the \"CameraId\" of an \"Icon Generator\" in the scene."
      }
      Overrides {
        Name: "cs:IconCameraId:category"
        String: "Custom"
      }
      Overrides {
        Name: "cs:IconCameraId:subcategory"
        String: "Icon"
      }
      Overrides {
        Name: "cs:IconAsset:tooltip"
        String: "The image or template to use for an icon. If \"IsKitbashed2DIcon\" is true, this should be a UI template. If \"Is3DIcon\" is true, this should be a 3D object template. If \"IsImageIcon\" is true, this should be an image/brush asset."
      }
      Overrides {
        Name: "cs:IconAsset:category"
        String: "Custom"
      }
      Overrides {
        Name: "cs:IconAsset:subcategory"
        String: "Icon"
      }
      Overrides {
        Name: "cs:IsKitbashed2DIcon:tooltip"
        String: "If true, the \"IconAsset\" should point to a UI template. This template will be spawned as the icon."
      }
      Overrides {
        Name: "cs:IsKitbashed2DIcon:category"
        String: "Custom"
      }
      Overrides {
        Name: "cs:IsKitbashed2DIcon:subcategory"
        String: "Icon"
      }
      Overrides {
        Name: "cs:Is3DIcon:tooltip"
        String: "If true, the \"IconAsset\" should point to a 3D object template. An image of this template will be used as the icon."
      }
      Overrides {
        Name: "cs:Is3DIcon:category"
        String: "Custom"
      }
      Overrides {
        Name: "cs:Is3DIcon:subcategory"
        String: "Icon"
      }
      Overrides {
        Name: "cs:IsImageIcon:tooltip"
        String: "If true, the \"IconAsset\" should point to an image/brush asset. This will be used as the icon."
      }
      Overrides {
        Name: "cs:IsImageIcon:category"
        String: "Custom"
      }
      Overrides {
        Name: "cs:IsImageIcon:subcategory"
        String: "Icon"
      }
      Overrides {
        Name: "cs:OutputText:tooltip"
        String: "(Optional) Text to use to display the Recipe output. Will be autogenerated from the Drops data if left blank."
      }
    }
    Assets {
      Id: 11569295798238027817
      Name: "Fantasy Sack 008"
      PlatformAssetType: 9
      PrimaryAsset {
        AssetType: "PlatformBrushAssetRef"
        AssetId: "UI_Fantasy_Equip_Sack_008"
      }
    }
  }
  SerializationVersion: 125
  VirtualFolderPath: "Data"
}
